name: Báo lỗi
description: Báo cáo lỗi có thể tái hiện
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Vui lòng cung cấp đủ thông tin để có thể tái hiện lỗi.
  - type: input
    id: summary
    attributes:
      label: Tóm tắt
      placeholder: Mô tả ngắn gọn lỗi gặp phải
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Các bước tái hiện
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Hành vi mong đợi
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Hành vi thực tế
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Môi trường
      placeholder: Phiên bản macOS, phiên bản Xcode
